# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
run_gibbSimple <- function(adj, weights, alpha0, alpha1, R, N, start) {
    .Call('_gibbsMRF_run_gibbSimple', PACKAGE = 'gibbsMRF', adj, weights, alpha0, alpha1, R, N, start)
}

